### ISSUE TITLE
Update queries support

### ISSUE THREAD

**Issue by NotCoffee418** [NotCoffee418/TrinityCreator#100]
load in existing values, allow users to update relevant values

**Comment by T1ti** [comment]
Being able to update existing items rather than only adding new ones would be awesome

**Comment by NotCoffee418** [comment]
@T1ti Items specifically should already have that option (since overriding them is the only chance of getting them to work in wotlk).

As for everything else, it's coming: 2d832796878184b67d94eb31c902c14875a199d8 cc57afae7ef39a95347619014cb14e228bb417bb
