### ISSUE TITLE
"Find" buttons not working with Vanilla

### ISSUE THREAD

**Issue by T1ti** [NotCoffee418/TrinityCreator#104]
Using Vmangos emulator : 

"Map" crashes the tool
"Faction" crashes the tool
"Title" crashes the tool
"item is working"
"Quest" returns a database error "unknown column 'ID' in 'order clause'" but the emulator profile changes it to entry instead of ID. No crash, only error and not being able to load.
'Creature" works
"gobject" works
"spell" crashes the client
"emote" works

Crashes all have  this as error message and then nothing

[2020-06-04 20:08:33.800][Info] DBC: DBC directory E:\WoWModding\World of Warcraft 1.12\\dbc appears to be valid.
[2020-06-04 20:08:33.802][Info] DBC: Attempting to load DBC file: E:\WoWModding\World of Warcraft 1.12\\dbc\Map.dbc

**Comment by NotCoffee418** [comment]
I can't replicate it. Can you post the full log please?
Are you using the new build from yesterday?

**Comment by NotCoffee418** [comment]
EDIT: It seems to only crash when trying to use DBC lookups.
I'll prevent the crash but I don't think I can properly fix it.

As a workaround, try binding it to a 3.3.5a dbc folder instead.
