### ISSUE TITLE
Item Creator - Default BuyCount

### ISSUE THREAD

**Issue by Variona** [NotCoffee418/TrinityCreator#107]
Not a bug but a request. With the item creator can you have the buy count default to 1? Some item types hide the buy count setting and then my logs yell at me for having an item with a 0 buy count item if I forget to change it manually.

Cheers

**Comment by illfated** [comment]
😉 I can only offer my sympathy with the troubles you get when forgetting to set the buy count. Your feature request looks fair to me.

**Comment by NotCoffee418** [comment]
Thanks for the report. I'll see if i can get some more changes today & push it today. ^^
