### ISSUE TITLE
Item Creator - Librams, Idols, Totems, and Sigils

### ISSUE THREAD

**Issue by Variona** [NotCoffee418/TrinityCreator#111]
Hello, I noticed that when making any 'Relic' type item that you can't change the Equip section to properly reflect that. You have to go into your database to change it. For my version its InventoryType and the correct ID would be 28. What would probably be ideal would be to simply remove the other options and just force the relic slot. Granted maybe someone out there will want to make a Libram headpiece.

Cheers!

![image](https://user-images.githubusercontent.com/5630669/86407956-a7c61f80-bc7b-11ea-9503-5c93516cf1cf.png)

![image](https://user-images.githubusercontent.com/5630669/86407976-b6acd200-bc7b-11ea-9a8a-947f0f7768cf.png)

**Comment by NotCoffee418** [comment]
Yeah there's quite a few of these in the item list that don't do anything. I'm guessing nobody really needs them and the people who do just create it manually.
Thanks for the report, at least this specific one is fixed now.
