### ISSUE TITLE
Problem Opening the program

### ISSUE THREAD

**Issue by tinypockett** [NotCoffee418/TrinityCreator#113]
Opens a Browser and says "An error occurred in the application in use" or something like that." If i redownload does the same thing! If i try to find a file opener just gives me adresses that are invalid.

**Comment by tinypockett** [comment]
also says  I'm missing a file, dunno wat it is

**Comment by NotCoffee418** [comment]
Which operating system are you using?
Does this happen right when starting the application?
Is this the first time running the application on this system?
Can you attach some screenshots?
Can you attach log files? (Located in %localappdata%\NotCoffee418\TrinityCreator\Logs)

**Comment by tinypockett** [comment]
I think the only problem is that i don't know with what to open my files, the program i use only shows up in text.
What are you using? Anyway, I have 1.1.1, and also i searched for 1.1.1.113. 
Where can i get it? I got a WotLK Client.
I think that's all. I'm just dumb. Thanks!

**Comment by NotCoffee418** [comment]
I'm sorry, I can't help with that little information.
You are using Windows, right? It won't work on mac or linux.
Did you follow the instructions [here](https://github.com/NotCoffee418/TrinityCreator)?

**Comment by tinypockett** [comment]
I think that's all sorry. I didn't meant to waste your time or piss you off, didn't install a supported emulator! Thanks a lot though!

**Comment by NotCoffee418** [comment]
Don't worry, I'm not upset. Sorry if it sounded that way. Just a bit confused as to what's going on. :)
