### ISSUE TITLE
Creature Creator Error

### ISSUE THREAD

**Issue by Variona** [NotCoffee418/TrinityCreator#117]
Hey, I started to make a profile for AzerothCore and they have 'mindmg', 'maxdmg', 'minrangeddmg', 'maxrangeddmg'...etc columns in the creature_template table.

When I go to make a creature I use these fields as they are the same for the most part (AC doesn't use armor, health, or mana)
![image](https://user-images.githubusercontent.com/5630669/109573337-e1765100-7abc-11eb-9974-b5e76f9d66bc.png)

However I get 2 separate errors when I try to make a creature. The first being: 
![image](https://user-images.githubusercontent.com/5630669/109573478-29957380-7abd-11eb-8b77-c54cca65e1d2.png)

Which is why I detailed the above information. I suspect it could be an issue with my profile, that I'm just not seeing or that perhaps the detailed stats section is already using 'mindmg' somewhere?

The second error, which I get right after pressing Ok on the first is: 
![image](https://user-images.githubusercontent.com/5630669/109574037-619cb680-7abd-11eb-8f98-96003638117e.png)

I have no idea what the CommandText property is or could be. I checked my profile and there isn't a field for it and there isn't a column in my database that uses it either.

I've uploaded my profile here. If you can shed some light on this issue I'd be very grateful. :)
.txt as you cannot upload .json on github
[Variona-AC2021-Rev1.txt](https://github.com/NotCoffee418/TrinityCreator/files/6065111/Variona-AC2021-Rev1.txt)

**Comment by NotCoffee418** [comment]
You have mindmg defined twice. as `MinMeleeDmg` and `MinDmg`.
Id say disable `MinMeleeDmg` if theres no field for it. Do the same with `MaxDmg `and `MaxMeleeDmg`
The second and third error are caused by the first error so they will also disappear.

**Comment by Variona** [comment]
Don't worry about the delay, I appreciate help.

I disabled Min and MaxMeleeDmg as you suggested and now I am receiving an entirely different error. Apparently there is a syntax error being created somewhere now. I looked through the .sql file it outputs and couldn't find anything that stood out to me, though I'm clearly no expert.

Here's a screenshot of the new error. Also I included the new profile just incase you needed it. Cheers
[Variona-AC2021-Rev1.txt](https://github.com/NotCoffee418/TrinityCreator/files/6104141/Variona-AC2021-Rev1.txt)

![image](https://user-images.githubusercontent.com/5630669/110382215-93b39880-8028-11eb-9e78-01bce0699c92.png)

**Comment by NotCoffee418** [comment]
Looks like 'rank' as a column name is causing issues with newer versions of mysql.

> RANK is a reserved word starting with MYSQL 8.0.2 (the version you upgraded to). That's the reason why you get the error.
> 
> To solve it is simple as adding backticks ` around RANK.

[source](https://stackoverflow.com/questions/52146194/query-syntax-issue-upgrading-to-mysql-8-from-5-7)

**Comment by NotCoffee418** [comment]
fixed it in a minor patch, you can just keep your profile the way it is and it should work around this this issue when exporting.

**Comment by Variona** [comment]
Works like a charm! Thanks!
