### ISSUE TITLE
Error 🗿👍

### ISSUE THREAD

**Issue by DsaNovikovtaran** [NotCoffee418/TrinityCreator#125]
![1642864611858281540580](https://user-images.githubusercontent.com/97804361/150644412-58c86ce7-8b3e-4d88-8ce8-784cc62eb2e0.jpg)

**Comment by NotCoffee418** [comment]
did you have internet access when this error occurred?
have you tried restarting the application?

**Comment by DsaNovikovtaran** [comment]
> 

I tried absolutely everything, delete then download, delved into the config, tried Repair, reboot, even tried downloading the old version

**Comment by NotCoffee418** [comment]
what happens when you open this url in your browser? https://github.com/NotCoffee418/TrinityCreatorProfiles/archive/master.zip

**Comment by NotCoffee418** [comment]
for whatever reason, it seems that your trinitycreator cant connect to that file. I've had someone report this issue before but i've never been able to reproduce it.

As a sketchy workaround you can manually download the profiles from one of thse URLs:
https://github.com/NotCoffee418/TrinityCreatorProfiles/archive/refs/heads/master.zip
https://github.com/NotCoffee418/TrinityCreatorProfiles/archive/master.zip
https://github.com/NotCoffee418/TrinityCreatorProfiles/
(it would help me if you could tell me if any or all of these links work for you in your browser.)  

Then navigate to `%localappdata%\NotCoffee418\TrinityCreator\Profiles`.  
You can do this by pressing Win+R on your keyboard and typing %localappdata%
Find/open or create the folder NotCoffee418  
Inside of that find/open or create the folder TrinityCreator
Inside of that find/open or create the folder Profiles

Then paste the contents of the zip folder in there and you should at least be able to run the application regardless of the error.

**Comment by DsaNovikovtaran** [comment]
Sorry, unfortunately all these sites do not work for me, but I dug around and downloaded the Trinity Core profile, if it's not a secret, can you tell me under what kind of file you need to download?

**Comment by NotCoffee418** [comment]
very strange... i'll attach the file here for you.
[TrinityCreatorProfiles-master.zip](https://github.com/NotCoffee418/TrinityCreator/files/7918984/TrinityCreatorProfiles-master.zip)

The way it works is is downloads the profiles, which are the things that tell the program which field goes where in the database, from github, this website.  
The fact that these don't work for you while i am talking to you on github is very odd.  
 
For whatever reason it seems you cannot access that particular repository while this one works fine.

**Comment by DsaNovikovtaran** [comment]
Should it be directly transferred to profiles with a zip file or unarchived and then all the files there?

**Comment by NotCoffee418** [comment]
they should be extracted. the folder structure should look something like this:
![image](https://user-images.githubusercontent.com/9306304/150650273-2d2762d7-d746-4edd-bd67-d4ab8f6e1e19.png)

**Comment by DsaNovikovtaran** [comment]
You need to throw all this directly into the folder, right?

**Comment by NotCoffee418** [comment]
yes sir

**Comment by DsaNovikovtaran** [comment]
YES, thank you for helping me, I just tried to understand what the problem was with my father for a long time and finally we solved it, thank you. :)

**Comment by NotCoffee418** [comment]
sorry for the trouble, best of luck with your creations!
