### ISSUE TITLE
MySQL Error - Index Reserved?

### ISSUE THREAD

**Issue by Variona** [NotCoffee418/TrinityCreator#126]
Hey! I'm making a profile for AzerothCore and noticed an issue.

[Index appears to be a reserved word.](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-I)

`INSERT INTO creature_template_spell (CreatureID, Spell, Index) VALUES (190129, 123, 0);`

That's what TrinityCreator generated

Maybe it should generate Index within ``

Cheers

**Comment by Variona** [comment]
Call back to #117

**Comment by NotCoffee418** [comment]
Sorry for the delay. Fixed in baba54a19823c75a1020139d08841fb9506832f3
