### ISSUE TITLE
Possible update for MySql.Data.dll?

### ISSUE THREAD

**Issue by JyriaLycion** [NotCoffee418/TrinityCreator#127]
With the recent changes from 8.0.27 to 8.0.29 the current MySql.Data.dll cannot properly connect to the database anymore. Is there any chance for a update to come out to adress this issue? Or is it possible to somehow swap the .dll for a newer version?

**Comment by NotCoffee418** [comment]
Fixed in a50852bcddf3d1a688ceefd1cf954eff5fce111d. 
You can restart the application and you'll be prompted to update to the new version with the latest MySql.Data.dll.
