### ISSUE TITLE
Data from the database is not pulled up

### ISSUE THREAD

**Issue by SQWIZI1337** [NotCoffee418/TrinityCreator#129]
Data from the database is not pulled up

**Comment by NotCoffee418** [comment]
In the lookup tool? Is your database connection configured correctly in Trinity Creator?

**Comment by SQWIZI1337** [comment]
Yes

**Comment by NotCoffee418** [comment]
Are there errors or anything to indicate what's wrong?

The other option is, you're connected to an empty database or something else unusual or wrong about your configuration.

I haven't really had anyone else complain about it being broken so most likely, assuming there is no error being shown, theres something unusual or wrong about your setup.

Any more details could help me identify whats going on though.

**Comment by SQWIZI1337** [comment]
![image](https://user-images.githubusercontent.com/114282670/215863952-66ca33cb-fe63-4e2f-80cc-adedba195f57.png)

**Comment by NotCoffee418** [comment]
Looks like you're target database is different from the profile you've
selected.
Make sure you're using the correct profile for the emulator and version
you're using.

It may also be possible that Trinity Creator doesnt support your emulator
at all. It only supports a small number of emulators right now, but there
is the ability to add custom support.

If it doesn't work, let me know which emulator and version you're using,
and which profile you're using it with so i cam try to replicate it.
