### ISSUE TITLE
Problem with Data base

### ISSUE THREAD

**Issue by ExcaroX** [NotCoffee418/TrinityCreator#130]
![image](https://user-images.githubusercontent.com/125036586/218247794-ec909d1c-99d5-43bb-9387-571c0d58bb34.png)

Im using elunatrinity latest engine

**Comment by NotCoffee418** [comment]
I don't think that's a supported emulator. 
I'm not currently working on this app at all, but you can [add support yourself](https://github.com/NotCoffee418/TrinityCreator/wiki/Adding-Emulator-Support) if it's worth it to you.
And if you do, feel free to share it so other people can use it as well.  

You can pm me on [discord](https://discord.gg/gUXwShK) if the instructions are unclear.

**Comment by ExcaroX** [comment]
the discord link is invalid can you give me your discord or new invite ?

**Comment by ExcaroX** [comment]
Yo guys if anyone have the problem like me with this same error just download MySql 5.7 and delete the MySql 8.7 and everything will work fine :)

**Comment by NotCoffee418** [comment]
huh... thats an unexpected cause of the issue. It should actually be fixable pretty easily if that's it.

**Comment by ExcaroX** [comment]
![image](https://user-images.githubusercontent.com/125036586/218779622-2e07534e-b243-4458-87c6-e0e9a0df961b.png)
jada told me this but not work

**Comment by NotCoffee418** [comment]
This issue should be fixed in the new version v1.1.5
