### ISSUE TITLE
Can't connect to mysql

### ISSUE THREAD

**Issue by Dreyzx** [NotCoffee418/TrinityCreator#131]
Hi i can't connect mysql i have connection test failed: SSL Authentication error

![image](https://github.com/NotCoffee418/TrinityCreator/assets/111538415/5a4448f1-490c-4b05-b966-578ca180a6ab)

**Comment by NotCoffee418** [comment]
Can you confirm that you can access the world database using the same
credentials from the same machine using another tool like HeidiSQL?

**Comment by Dreyzx** [comment]
Yes

**Comment by NotCoffee418** [comment]
I can't replicate it with or without SSL enforced.

Can you tell me more about your setup:  
- Are you on the latest version of TrinityCreator?
- Which version of MySQL / MariaDB are you using (or which repack)?
- Do you have any specific SSL / TLS settings on your MySQL server?

Any additional information is helpful; eg, anything you need to add to your connection string or settings you have to explicitly add to connect to your server.
