### ISSUE TITLE
Enable editing creations from DB

### ISSUE THREAD

**Issue by figback65** [NotCoffee418/TrinityCreator#42]
Great tool man. I love it. I wish it had 1 more feature to this to complete the design for me. Being able to lookup and edit creature, quest, item, so forth. You already have the fields layed out for the editing, just needs a search and population. That way people do not have to download all the stuff needed for Keia's web based editor and basically be hosting a private webserver. Your tool could do it all! I hope one day you decide to add this feature in. 

Keep up the good work! Thank you for the tool!!!!!!!

**Comment by NotCoffee418** [comment]
Closing. This won't happen, sorry.
There's too many weird variables for this to be reasonably do this while keeping bug-free multi-emulator support.
It's annoying to modify certain columns (like flags) with HeidiSQL or similar software but it's just not worth the amount of black magic fuckery i'd have to do to get it working right.
