### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by NotCoffee418** [NotCoffee418/TrinityCreator#51]
As usual, end of the day for probably a year and the updater is broken.
Probably due to `var proc = new ProcessStartInfo("TrinityCreatorUpdater.exe");` in TrinityCreator.exe, which probably requires a full path.

GL with that future me.

**Comment by Nadromar** [comment]
Hi past me and future me. Consider impelementing AutoUpdater.net and using a build (release) command to zip the contents for the update instead of attempting to fix this broken mess.

**Comment by NotCoffee418** [comment]
Fixed in 85eaa6383f8d1ddb5efcdf946d09404e61f63651
