### ISSUE TITLE
NPC Creator 

### ISSUE THREAD

**Issue by eric9966** [NotCoffee418/TrinityCreator#57]
Every time I create an NPC, I have to remove the trainer_type, trainer_spell, trainer_class, trainer_race, and InhabitType fields. Seems it may be out of date?

**Comment by illfated** [comment]
Makes me wonder if the latest trainer changes in TC 335 branch source code has not been taken into account yet.

**Comment by Nadromar** [comment]
If you've downloaded the standard database and don't have updates enabled, please ensure you have the 335a64 emulator selected in Top Menu > Select Emulator.

If you're running an updated database and this is a new change, you can export the structure of your world DB and upload it here (not the data itself please) then I'll fix it for ya.

Unfortunately these issues will continue to occur occasionally as they change the DB structure.
I don't even have a compiled build of TC anymore so I can't check it myself. :/

And if you're not running TC335a let me know which emulator you are using.

**Comment by JohnnyMccrum** [comment]
Also having this same issue. Any progress on this as it was several months ago or is this project on hold?

**Comment by illfated** [comment]
See the reply from Nadromar above your comment:

> If you're running an updated database and this is a new change, **you can export the structure of your world DB and upload it here** (not the data itself please) **then I'll fix it for ya.**

**Comment by JohnnyMccrum** [comment]
Here is my World DB structure - data:

https://ufile.io/ic77ho58

**Comment by illfated** [comment]
Very well. Let's hope @Nadromar is prepared to download it within the available 29 days (+ some hours) and use the DB structure to improve the Creator source.

**Comment by NotCoffee418** [comment]
Sadly I did not. The good news is, soon people will be able to create and modify profiles so stuff so you won't have to rely on me to create different versions for every version of every emulator.

Any future discussion about this issue can be done at #58
