### ISSUE TITLE
"Unknown Column 'Trainer Type' in 'Field list'

### ISSUE THREAD

**Issue by ghost** [NotCoffee418/TrinityCreator#63]
error:
**"Unknown Column 'Trainer Type' in 'Field list'** 

How to recreate error:
- 3.3.5 TrinityCore
- Current Database. (335.19061_2019_06_15) 15th of June 2019 update. 
- when attempting to add new Creature to database.

Also seems like this error also applies to:  
**'trainer_spell', 'trainer_class', 'trainer_race'**, and **'InhabitType'** fields, resistances and spells. It is possible for me to slightly modify the code and remove these features so that it adds a non-functional creature to the database. 

Seems like this error was reported back in March, you mentioned that you didn't have a compiled version of TrinityCreator in March.  Is TrinityCreator still being updated?

**Comment by illfated** [comment]
More or less the same type of issue as #57.

**Comment by Clotic93** [comment]
got same. Hope he updates it:)

**Comment by NotCoffee418** [comment]
Working on it!
Closing this issue since i'll re-do the up-to-date trinitycore profile when the profile system is implemented. See #58 .
