### ISSUE TITLE
Quest Creator Error

### ISSUE THREAD

**Issue by Variona** [NotCoffee418/TrinityCreator#64]
Hello, I have an issue when creating a quest. I've noticed that when I change the Time limit it also changes the Player kills to be the same value.

![image](https://user-images.githubusercontent.com/5630669/70753136-105ea680-1d02-11ea-9d86-142bd7deb8f6.png)
As you can see they are right next to each other but when you change one the other changes as well. 
I'm using the TDB 335.64 emulator.

![image](https://user-images.githubusercontent.com/5630669/70754797-21111b80-1d06-11ea-87d9-a5ba05c17327.png)

This isn't a huge issue as I can add the time limit into the DB manually but its a rather odd bug.

Cheers.

**Comment by NotCoffee418** [comment]
Fixed in 027cc2cbeb823c3bc6c846c0d7a29302ce0d8a5f
