### ISSUE TITLE
Ranged weapon auto define RangedModRange

### ISSUE THREAD

**Issue by NotCoffee418** [NotCoffee418/TrinityCreator#69]
if (item.InventoryType.Id == 15 || item.InventoryType.Id == 26)
                kvplist.Add("RangedModRange", "100");

This was done in the old sql export. Have a TrinityItem property for it instead with an event handler or something.

Property is created but not assigned.

**Comment by NotCoffee418** [comment]
Also.. What is 26? 15 is "Ranged"

**Comment by illfated** [comment]
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130222/item+template

ID | Slot Name | ID | Slot Name
-- | -- | -- | --
0 | Non equipable | 15 | Ranged (Bows)
1 | Head | 16 | Back
2 | Neck | 17 | Two-Hand
3 | Shoulder | 18 | Bag
4 | Shirt | 19 | Tabard
5 | Chest | 20 | Robe
6 | Waist | 21 | Main hand
7 | Legs | 22 | Off hand
8 | Feet | 23 | Holdable (Tome)
9 | Wrists | 24 | Ammo
10 | Hands | 25 | Thrown
11 | Finger | 26 | Ranged right (Wands, Guns)
12 | Trinket | 27 | Quiver
13 | Weapon | 28 | Relic
14 | Shield |   |

**Comment by NotCoffee418** [comment]
Now auto defined in TrinityItem when InventoryType changes. c8e5b9178026b555984e229d3acd3605999a0b9c
