### ISSUE TITLE
Multiple Issues with Item Creator

### ISSUE THREAD

**Issue by Variona** [NotCoffee418/TrinityCreator#81]
When making a new item it doesn't automatically set the Material and Sheath columns anymore.

I updated to the latest version and it no longer sets them properly. They remain at 0 unless I change them manually.

On another note can you also add a check box to the 'Weapon Disclaimer' saying I understand and don't want to see this popup anymore? If I close the program and reopen it this dialog will pop up once more.

One other issue I've noticed is that if I click 'Create new item' which normally just clears the form for a new item it now stalls for a second then crashes.

**Comment by NotCoffee418** [comment]
Thanks for the report!
Fixed in 3e294e3173ee818f3a49ada11d63e91f9a7aadaa
I'll publish a new build within the next few hours after looking for similar issues.
