### ISSUE TITLE
Item Creator Totally Broken

### ISSUE THREAD

**Issue by Variona** [NotCoffee418/TrinityCreator#82]
I cannot create any items. The different armors, weapons, containers, consumables, gems, etc all give out errors.

Here are some of them. 

![image](https://user-images.githubusercontent.com/5630669/73395621-e5c6ae00-42ad-11ea-8e48-73590ad4a079.png)

![image](https://user-images.githubusercontent.com/5630669/73395634-e95a3500-42ad-11ea-99d6-3ce80976639d.png)

![image](https://user-images.githubusercontent.com/5630669/73395642-ec552580-42ad-11ea-8d67-19022d4d3c61.png)
Plate + Shields
![image](https://user-images.githubusercontent.com/5630669/73395651-ef501600-42ad-11ea-963e-c65951070525.png)

This is for weapons, gems, containers, quivers, quests, reagents, keys, miscellaneous, librams,
idols, totems, sigils
![image](https://user-images.githubusercontent.com/5630669/73395657-f2e39d00-42ad-11ea-8bc3-5a6443b3eaf4.png)

Glyphs produce:
![image](https://user-images.githubusercontent.com/5630669/73396187-e14ec500-42ae-11ea-882c-4392381f016e.png)

Going to try a fresh install. These happened after the update earlier.

**Comment by Variona** [comment]
Fresh install did not help.

**Comment by illfated** [comment]
Could this possibly have anything to do with the version of the core or DB you are using, before & after updating your version of TrinityCreator?

**Comment by NotCoffee418** [comment]
Looks like i broke something there :o
I'll look into it... That's quite an odd series of errors. Especially considering i don't have it on my end.

I might need more info from you, I'll let you know.

**Comment by Variona** [comment]
I think I might have figured out why. Give me a few minutes to test and make sure.

**Comment by NotCoffee418** [comment]
Material was being exported  as the whole class rather than it's ID.
Still odd that it's not happening on my end though..

**Comment by Variona** [comment]
I think its the emulator profile that's the issue. I tried creating my own but its still not working as I'm getting the same errors. I'm going to download an older revision and see if it works.

**Comment by NotCoffee418** [comment]
Pushed an update. Please restart the application and let me know if it works.
Sorry about that. :o

**Comment by Variona** [comment]
The issue is solved with the latest update! And my profile seems to work so far. I'm going to polish it up then send it your way to host. Cheers!
