### ISSUE TITLE
DBC Configuration

### ISSUE THREAD

**Issue by Variona** [NotCoffee418/TrinityCreator#83]
I have my DBC directory set and it seems to work just fine (lookups show results from my custom dbc files) but it still gives me a weird error every time I click save.

![image](https://user-images.githubusercontent.com/5630669/73402917-596fb780-42bc-11ea-8121-1bd6fa9051c2.png)

If I click yes then it will just open up another window and repeat. If I click no it all seems to work just fine though. Cheers

**Comment by NotCoffee418** [comment]
Does your custom DBC directory contain all other DBC files?
The check for "valid dbc files" is a bit broken though... Currently it only checks for AreaTable.dbc.
I can look into adding an override DBC directory as an advanced setting if that's applicable to you.
You'd point dbc directory to a folder containing all DBC files and a hidden option to select a folder containing your custom dbcs.

**Comment by Variona** [comment]
AreaTable.dbc is within the folder. 

![image](https://user-images.githubusercontent.com/5630669/73407259-8aed8080-42c6-11ea-9792-c7f0f5a4b9f0.png)

Maybe its because of being on a network drive? I don't know, that's the other thing that pops out to me as a possibility.

**Comment by NotCoffee418** [comment]
Interesting... Would you mind providing a log file of a run where this occurs?
1. Open TrinityCreator.
2. Replicate the issue
3. Click in the top menubar on Info > View Log Files
4. Paste the newest file in a comment

This only occurs when clicking "Save" in DBC Config window or does it happen whenever you run a dbc query?

**Comment by NotCoffee418** [comment]
Should be fixed in 02290c2220322a4768c8200c10474b556d1601d6. Can you confirm?
