### ISSUE TITLE
Images for documentation

### ISSUE THREAD

**Issue by NotCoffee418** [NotCoffee418/TrinityCreator#85]
![profilecreator-row](https://user-images.githubusercontent.com/9306304/73416045-f1e55680-4313-11ea-9ea0-6e3747641ba1.JPG)

**Comment by illfated** [comment]
Just out of curiosity: is the third column ([table_names]) size limited in the UI, so there is no chance to see more of the names than the above?

**Comment by NotCoffee418** [comment]
No, there is no practical purpose. It's honestly just bad design. :P
I'll fix that in a bit. ^^
