### ISSUE TITLE
DBC tutorial please

### ISSUE THREAD

**Issue by Daviddiff** [NotCoffee418/TrinityCreator#88]
Hi, what do I do to make it work?
![Výstřižek](https://user-images.githubusercontent.com/60797891/74068095-00f69380-49fb-11ea-9d1e-ff5aa1408c86.PNG)
thank you for answer

**Comment by illfated** [comment]
Looks like TrinityCreator expects to find the DBC files in a specific folder. I have not used TrinityCreator myself yet, so I can only guess that A) there is a setting in the program to tell where the default DBC files are located, or B) the DBC files need to be in a Core subfolder for the emulator version you are using. Maybe there is some form of interaction between the Core you are using and TrinityCreator, which will affect the expected location of the DBC files, but I don't know yet.

**Comment by NotCoffee418** [comment]
Hmh that's the second time this has been reported.
It all looks correct assuming that's the directory with all your dbc files.

1) Are you using a WotLK client? 
2) Is the DBC folder you selected shipped with a repack? if so, which one?
3) Did you get a window prompting to "extract DBC files"?
4) Can you send me the relevant log file where you first tried to set up DBC.

You can find log files in the top menu under Info > Show Log Files.
If you're not sure which one it is, just put them all in a zip file and send them over.

**Comment by Elarose** [comment]
Same thing, and I have used this but an older version, yet now.

[0221/034511.457:WARNING:resource_bundle.cc(358)] locale_file_path.empty() for locale 
[0221/034511.457:ERROR:main_delegate.cc(714)] Could not load locale pak for en-US

**Comment by NotCoffee418** [comment]
Fixed in 02290c2220322a4768c8200c10474b556d1601d6
