### ISSUE TITLE
DBC Path broken

### ISSUE THREAD

**Issue by Lagman01** [NotCoffee418/TrinityCreator#89]
I tried multiple ways before posting this here. It doesn't matter what I do, setting up the DBC path gives me the same error:
![image](https://user-images.githubusercontent.com/61359089/75096680-d74b7980-556f-11ea-8236-dc742cee3240.png)

I'm using a 3.3.5a client (AC-Web Repack). I can see all my DBC files and they're valid. Using the latest version of Trinity Creator. Please help, you might have to push another update.

**Comment by illfated** [comment]
Possibly related to the discussion in ticket **#88** (**DBC tutorial please**)?

**Comment by NotCoffee418** [comment]
Fixed in 02290c2220322a4768c8200c10474b556d1601d6
