### ISSUE TITLE
Modern expansion support?

### ISSUE THREAD

**Issue by NoRRt** [NotCoffee418/TrinityCreator#90]
Support Patch 8.3 ?

**Comment by NotCoffee418** [comment]
I'll leave this open to look into it.
But I believe the structure is too different to properly support modern expansions even with the new profile system.
If that's the case, it won't happen.

**Comment by Thordekk** [comment]
that will be great

**Comment by Dannylew12** [comment]
Any update?

**Comment by NotCoffee418** [comment]
I won't be implementing it in TC, sorry
