### ISSUE TITLE
[Minor bug] Typo in "Ranged Attack Power' stat type

### ISSUE THREAD

**Issue by Variona** [NotCoffee418/TrinityCreator#92]
Says 'Attach' not 'Attack'.

![image](https://user-images.githubusercontent.com/5630669/79004597-ab358900-7b1a-11ea-90b8-1fb4ad903e42.png)

**Comment by illfated** [comment]
Nice typo. Can't exactly blame AutoCorrect for that either, since both words are valid dictionary words.

**Comment by NotCoffee418** [comment]
Typo's in an xml file that I didn't even realize was used, heh.
And this file might actually be the reason for another issue i'm having with items on 1.12.
The typo will be fixed in the next build. Thanks for reporting!
