### ISSUE TITLE
Must have a melee weapon equipped in main hand

### ISSUE THREAD

**Issue by Solvius** [NotCoffee418/TrinityCreator#94]
When ever i create a sword i can't use my spells and a message "Must have a melee weapon equipped in main hand" appears.

**Comment by NotCoffee418** [comment]
There's a [big disclaimer](https://github.com/NotCoffee418/TrinityCreator/raw/master/TrinityCreator/Resources/weapon-notice.rtf) that shows up when exporting weapons.
Basically, you need client side edits to make them work right in wotlk+.
Not much I can do about it sadly. :/
