### ISSUE TITLE
Creator Trinity

### ISSUE THREAD

**Issue by Lovegun1984** [NotCoffee418/TrinityCreator#97]
Where do I install the creator of the trinity? Thanks you

**Comment by illfated** [comment]
https://github.com/NotCoffee418/TrinityCreator/blob/master/README.md

The downloaded file is a .MSI installer file, which installs the program so you don't need to select any folder.

**Comment by Lovegun1984** [comment]
![image](https://user-images.githubusercontent.com/65744884/82628394-b7514380-9bba-11ea-8620-6660f957524e.png)

**Comment by Lovegun1984** [comment]
I have problems with this ... how should I configure it?

**Comment by Lovegun1984** [comment]
![image](https://user-images.githubusercontent.com/65744884/82630057-9ccd9900-9bbf-11ea-8040-3d92a789d0de.png)

**Comment by illfated** [comment]
Looks like you don't have any TrinityCore server installed on the computer where you installed TrinityCreator.
You need to have a TrinityCore MySQL server running, with the databases used in the game, on the same computer as TrinityCreator.

It looks to me like you have only the game installed, connecting to a different computer where the TrinityCore servers are running. This will not work.

**Comment by Lovegun1984** [comment]
should i install the trinity creator in the wow trinity folder?

**Comment by Lovegun1984** [comment]
I have the trinity creator installed on disk C
and the game plus the database on disk G..that could be the problem?

**Comment by Lovegun1984** [comment]
Do you have an account in discord? to be able to speak more easily?

**Comment by illfated** [comment]
Sorry, I don't know what more to troubleshoot. You need to wait for a reply from @NotCoffee418 to get more help, if he is able to guess what is wrong on your computer.

The only thing I could make a guess at, based on your images above, is that you need to check the MySQL database login via either HeidiSQL, SQLyog og some other MySQL editor where you have to log in. Maybe you need to login as `root`, I don't know.

**Comment by NotCoffee418** [comment]
It just looks like a wrong login.
Open your `world.conf` file and enter the login information for the world database you'll find there.

**Comment by illfated** [comment]
Ah. Right. Could be outdated information about what the username & password is for the DB login.
"trinity" / "trinity" seems a bit outdated to me. Then again, I have not participated in the setup of your DB.

**Comment by NotCoffee418** [comment]
I'll assume this issue is resolved. Please reopen or create a new issue if you're still experiencing this problem.
